# // INFO: PRESET keymap: https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/keymap.toml


[[manager.prepend_keymap]]
on   = [ "e" ]
# // https://github.com/sxyazi/yazi/issues/591
# // REF: https://yazi-rs.github.io/docs/tips/#dropping-to-the-shell
run  = 'shell "~/helix/2407/hx $@" --block --confirm'
desc = 'Edit file with HELIX...'


# // https://gitee.com/DreamMaoMao/fg.yazi#usage

[[manager.prepend_keymap]]
on   = [ "f","g" ]
run  = "plugin fg"
desc = "find file by content (fuzzy match)"

[[manager.prepend_keymap]]
on   = [ "f","G" ]
run  = "plugin fg --args='rg'"
desc = "find file by content (ripgrep match)"

[[manager.prepend_keymap]]
on   = [ "f","f" ]
run  = "plugin fg --args='fzf'"
desc = "find file by filename"

