[manager]
ratio = [1,2,5]

[plugin]
prepend_previewers = [
  #{ name = "*.md", run = "glow" },

  { mime = "text/markdown", run = "glow" },

  { mime = "text/csv", run = "miller"},
]


# // REF: https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/yazi.toml
[opener]
edit = [
  # // OPEN file: `-R` for read-only
  { run = '${EDITOR:-vi} -R "$@"', desc = "$EDITOR", block = true, for = "unix" },
]

# // OKAY: Override `reveal` action
# reveal = [
#   # // Open file with HELIX...
#   { run = '~/helix/2407/hx "$@"', desc = "Helix", block = true, for = "unix" },
# ]
