" Generated by vim-plug
" Sun 22 Sep 2024 01:43:39 AM BST
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['nvim'].commit = '63685e1562ef53873c9764b483d7ac5c7a608922'
silent! let g:plugs['nvim-lspconfig'].commit = 'b064131428f6bbbbc905f4451ba6779fda334a3a'
silent! let g:plugs['nvim-treesitter'].commit = '929ca9c76ee20bb27cffbde4ee90583b6c54d616'
silent! let g:plugs['nvim-treesitter-context'].commit = '3d5390c49e3f8fe457b376df2a49aa39d75b7911'
silent! let g:plugs['nvim-treesitter-refactor'].commit = 'd8b74fa87afc6a1e97b18da23e762efb032dc270'
silent! let g:plugs['nvim-treesitter-textobjects'].commit = 'bf8d2ad35d1d1a687eae6c065c3d524f7ab61b23'
silent! let g:plugs['plenary.nvim'].commit = '2d9b06177a975543726ce5c73fca176cedbffe9d'
silent! let g:plugs['telescope.nvim'].commit = 'b5fd7f7ae0ea4537511077ed8ef4a6021cedba2f'
silent! let g:plugs['vim-airline'].commit = '81eca994860645acbb58442285cdd70df5c71d2b'

PlugUpdate!

